import { NextRequest, NextResponse } from "next/server";
import { cachedQuery, DB } from "@/lib/snowflake";

export async function GET(req: NextRequest) {
  const section = req.nextUrl.searchParams.get("section") || "dashboard";
  try {
    if (section === "dashboard") {
      const [kpiAndSentAndQuality, volume, intent] = await Promise.all([
        cachedQuery(`
          SELECT COUNT(*) AS TOTAL_CALLS, ROUND(SUM(CALL_DURATION_SECONDS)/60,1) AS TOTAL_DURATION_MINS, ROUND(AVG(CALL_DURATION_SECONDS)/60,1) AS AVG_DURATION_MINS,
            ROUND(SUM(CASE WHEN FIRST_CALL_RESOLUTION='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),1) AS FCR_RATE,
            ROUND(SUM(CASE WHEN CONVERSATION_SENTIMENT='Positive' THEN 1 ELSE 0 END)*100.0/COUNT(*),1) AS POSITIVE_SENTIMENT_PCT,
            ROUND(AVG(NET_PROMOTER_SCORE),0) AS AVG_NPS, COUNT(DISTINCT REPRESENTATIVE) AS ACTIVE_REPS,
            SUM(CASE WHEN CONVERSATION_SENTIMENT='Positive' THEN 1 ELSE 0 END) AS SENT_POSITIVE,
            SUM(CASE WHEN CONVERSATION_SENTIMENT='Negative' THEN 1 ELSE 0 END) AS SENT_NEGATIVE,
            SUM(CASE WHEN CONVERSATION_SENTIMENT='Neutral' THEN 1 ELSE 0 END) AS SENT_NEUTRAL,
            SUM(CASE WHEN CALL_QUALITY='Excellent' THEN 1 ELSE 0 END) AS Q_EXCELLENT,
            SUM(CASE WHEN CALL_QUALITY='Good' THEN 1 ELSE 0 END) AS Q_GOOD,
            SUM(CASE WHEN CALL_QUALITY='Average' THEN 1 ELSE 0 END) AS Q_AVERAGE,
            SUM(CASE WHEN CALL_QUALITY='Poor' THEN 1 ELSE 0 END) AS Q_POOR
          FROM ${DB}.TELECOM_CALL_RECORDINGS
        `, 30000),
        cachedQuery(`SELECT CALL_DATE, COUNT(*) AS CALL_COUNT, ROUND(AVG(CALL_DURATION_SECONDS)/60,1) AS AVG_DURATION_MINS FROM ${DB}.TELECOM_CALL_RECORDINGS GROUP BY CALL_DATE ORDER BY CALL_DATE`, 30000),
        cachedQuery(`SELECT CALL_INTENT, COUNT(*) AS CALL_COUNT, ROUND(AVG(CALL_DURATION_SECONDS)/60,1) AS AVG_DURATION_MINS, ROUND(SUM(CASE WHEN FIRST_CALL_RESOLUTION='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),1) AS FCR_RATE FROM ${DB}.TELECOM_CALL_RECORDINGS GROUP BY CALL_INTENT ORDER BY CALL_COUNT DESC`, 30000),
      ]);
      const r = kpiAndSentAndQuality[0] as Record<string, unknown>;
      const kpis = { TOTAL_CALLS: r.TOTAL_CALLS, TOTAL_DURATION_MINS: r.TOTAL_DURATION_MINS, AVG_DURATION_MINS: r.AVG_DURATION_MINS, FCR_RATE: r.FCR_RATE, POSITIVE_SENTIMENT_PCT: r.POSITIVE_SENTIMENT_PCT, AVG_NPS: r.AVG_NPS, ACTIVE_REPS: r.ACTIVE_REPS };
      const sentiment = [
        { CONVERSATION_SENTIMENT: "Positive", CALL_COUNT: r.SENT_POSITIVE },
        { CONVERSATION_SENTIMENT: "Negative", CALL_COUNT: r.SENT_NEGATIVE },
        { CONVERSATION_SENTIMENT: "Neutral", CALL_COUNT: r.SENT_NEUTRAL },
      ].filter((s) => Number(s.CALL_COUNT) > 0);
      const quality = [
        { CALL_QUALITY: "Excellent", CALL_COUNT: r.Q_EXCELLENT },
        { CALL_QUALITY: "Good", CALL_COUNT: r.Q_GOOD },
        { CALL_QUALITY: "Average", CALL_COUNT: r.Q_AVERAGE },
        { CALL_QUALITY: "Poor", CALL_COUNT: r.Q_POOR },
      ].filter((q) => Number(q.CALL_COUNT) > 0);
      return NextResponse.json({ kpis, sentiment, volume, intent, quality });
    }
    if (section === "calls") {
      const rows = await cachedQuery(`SELECT cr.AUDIO_FILE, cr.CUSTOMER_ID, cr.CALL_DATE, cr.CALL_DURATION_SECONDS, cr.REPRESENTATIVE, cr.CUSTOMER_NAME, cr.CALL_INTENT, cr.CONVERSATION_SENTIMENT, cr.FIRST_CALL_RESOLUTION, cr.CALL_QUALITY, cr.NET_PROMOTER_SCORE, cr.ISSUE, cr.RESOLUTION, cr.NEXT_STEPS, cr.PURPOSE_OF_CALL, cr.CONVERSATION_SUMMARY, cr.CONVERSATION_STRUCTURED, cu.PLAN_NAME, cu.SEGMENT, cu.TENURE_MONTHS, cs.CHURN_RISK_LEVEL FROM ${DB}.TELECOM_CALL_RECORDINGS cr JOIN ${DB}.TELECOM_CUSTOMERS cu ON cr.CUSTOMER_ID=cu.CUSTOMER_ID LEFT JOIN ${DB}.TELECOM_CHURN_SCORES cs ON cr.CUSTOMER_ID=cs.CUSTOMER_ID ORDER BY cr.CALL_DATE DESC LIMIT 200`, 30000);
      return NextResponse.json(rows);
    }
    if (section === "reps") {
      const rows = await cachedQuery(`SELECT REPRESENTATIVE, COUNT(*) AS TOTAL_CALLS, ROUND(AVG(CALL_DURATION_SECONDS)/60,1) AS AVG_DURATION_MINS, ROUND(SUM(CASE WHEN FIRST_CALL_RESOLUTION='Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*),1) AS FCR_RATE, ROUND(SUM(CASE WHEN CONVERSATION_SENTIMENT='Positive' THEN 1 ELSE 0 END)*100.0/COUNT(*),1) AS POSITIVE_SENTIMENT_PCT, ROUND(AVG(NET_PROMOTER_SCORE),0) AS AVG_NPS FROM ${DB}.TELECOM_CALL_RECORDINGS GROUP BY REPRESENTATIVE ORDER BY TOTAL_CALLS DESC`, 30000);
      return NextResponse.json(rows);
    }
    return NextResponse.json({ error: "invalid section" }, { status: 400 });
  } catch (e: unknown) {
    return NextResponse.json({ error: String(e) }, { status: 500 });
  }
}
