import { NextRequest, NextResponse } from "next/server";
import { cachedQuery, DB } from "@/lib/snowflake";

export async function GET(req: NextRequest) {
  const cid = req.nextUrl.searchParams.get("cid");
  if (!cid) return NextResponse.json({ error: "cid required" }, { status: 400 });
  const esc = cid.replace(/'/g, "''");

  try {
    const [core, interactions, orchestration] = await Promise.all([
      cachedQuery(`
        SELECT cu.*, d.DEVICE_MODEL, d.DEVICE_OS, d.DEVICE_AGE_MONTHS, d.DEVICE_PAYMENT_REMAINING, d.DEVICE_BRAND,
               cs.CHURN_RISK_SCORE, cs.CHURN_RISK_LEVEL, cs.PRIMARY_RISK_FACTORS, cs.PREDICTED_CHURN_DATE, cs.RETENTION_PROBABILITY,
               cm.MEMORY_ID, cm.CHANNEL AS MEM_CHANNEL, cm.LANGUAGE, cm.LAST_INTENT, cm.ACTIVE_SPECIALIST, cm.LAST_SUMMARY, cm.OPEN_ACTIONS,
               cm.NEXT_BEST_ACTION AS MEM_NBA, cm.LAST_CONTACT_AT, cm.ESCALATION_STATUS, cm.REP_ASSIST_BRIEF
        FROM ${DB}.TELECOM_CUSTOMERS cu
        LEFT JOIN ${DB}.TELECOM_DEVICES d ON cu.CUSTOMER_ID=d.CUSTOMER_ID
        LEFT JOIN ${DB}.TELECOM_CHURN_SCORES cs ON cu.CUSTOMER_ID=cs.CUSTOMER_ID
        LEFT JOIN ${DB}.TELECOM_CONVERSATION_MEMORY cm ON cu.CUSTOMER_ID=cm.CUSTOMER_ID
        WHERE cu.CUSTOMER_ID='${esc}'
      `, 15000),
      Promise.all([
        cachedQuery(`SELECT USAGE_PERIOD, DATA_USED_GB, DATA_LIMIT_GB, DATA_OVERAGE_GB, VOICE_MINUTES, SMS_COUNT FROM ${DB}.TELECOM_USAGE WHERE CUSTOMER_ID='${esc}' ORDER BY USAGE_PERIOD DESC LIMIT 12`, 15000),
        cachedQuery(`SELECT BILL_DATE, TOTAL_AMOUNT, BASE_CHARGE, OVERAGE_CHARGES, PAYMENT_STATUS FROM ${DB}.TELECOM_BILLING WHERE CUSTOMER_ID='${esc}' ORDER BY BILL_DATE DESC LIMIT 12`, 15000),
        cachedQuery(`SELECT PERIOD, APP_LOGINS, WEB_VISITS, CHAT_INTERACTIONS, LAST_CONTACT_CHANNEL FROM ${DB}.TELECOM_ENGAGEMENT WHERE CUSTOMER_ID='${esc}' ORDER BY PERIOD DESC LIMIT 12`, 15000),
        cachedQuery(`SELECT PERIOD, AVG_DOWNLOAD_MBPS, AVG_UPLOAD_MBPS, AVG_LATENCY_MS, DROPPED_CALL_RATE FROM ${DB}.TELECOM_QOE WHERE CUSTOMER_ID='${esc}' ORDER BY PERIOD DESC LIMIT 6`, 15000),
        cachedQuery(`SELECT CASE_ID, CATEGORY, STATUS, PRIORITY, SENTIMENT, CREATED_AT FROM ${DB}.TELECOM_CASES WHERE CUSTOMER_ID='${esc}' ORDER BY CREATED_AT DESC LIMIT 20`, 15000),
        cachedQuery(`SELECT AUDIO_FILE, CALL_DATE, CALL_DURATION_SECONDS, REPRESENTATIVE, CALL_INTENT, CONVERSATION_SENTIMENT, FIRST_CALL_RESOLUTION, CALL_QUALITY, NET_PROMOTER_SCORE, ISSUE, RESOLUTION, NEXT_STEPS, PURPOSE_OF_CALL, CONVERSATION_SUMMARY FROM ${DB}.TELECOM_CALL_RECORDINGS WHERE CUSTOMER_ID='${esc}' ORDER BY CALL_DATE DESC LIMIT 20`, 15000),
      ]),
      Promise.all([
        cachedQuery(`SELECT i.INCIDENT_ID, i.INCIDENT_TYPE, i.SEVERITY, i.STATUS, i.AFFECTED_AREA, i.AFFECTED_SERVICES, i.ROOT_CAUSE, i.STARTED_AT, i.RESOLVED_AT, i.DURATION_HOURS, ii.IMPACT_LEVEL, ii.NOTIFIED, ii.CREDIT_AMOUNT FROM ${DB}.TELECOM_INCIDENT_IMPACT ii JOIN ${DB}.TELECOM_INCIDENTS i ON ii.INCIDENT_ID=i.INCIDENT_ID WHERE ii.CUSTOMER_ID='${esc}' ORDER BY i.STARTED_AT DESC LIMIT 10`, 15000),
        cachedQuery(`SELECT RECOMMENDATION_RANK, OFFER_NAME, OFFER_CATEGORY, PROPENSITY_SCORE, ESTIMATED_MONTHLY_VALUE, REASON, CHANNEL_PREFERENCE, VALID_UNTIL FROM ${DB}.TELECOM_NBA_RECOMMENDATIONS WHERE CUSTOMER_ID='${esc}' ORDER BY RECOMMENDATION_RANK LIMIT 10`, 15000),
        cachedQuery(`SELECT ACTION_ID, ACTION_CATEGORY, ACTION_NAME, AUTONOMY_LEVEL, CONFIRMATION_REQUIRED, CONFIRMATION_CAPTURED, APPROVAL_STATUS, EXECUTION_STATUS, ROLLBACK_ELIGIBLE, ROLLBACK_BY, AGENT_NAME, CUSTOMER_VISIBLE_SUMMARY, EVENT_TS FROM ${DB}.TELECOM_ACTION_AUDIT WHERE CUSTOMER_ID='${esc}' ORDER BY EVENT_TS DESC LIMIT 20`, 15000),
        cachedQuery(`SELECT RECOMMENDATION_ID, AGENT_NAME, INTENT, SUB_INTENT, RECOMMENDATION_TITLE, RECOMMENDATION_DETAIL, CONFIDENCE_SCORE, ACTION_TIER, REQUIRES_CONFIRMATION, HUMAN_APPROVAL_REQUIRED, EXPECTED_OUTCOME, PRIMARY_SIGNAL, SUPPORTING_SIGNALS FROM ${DB}.TELECOM_AGENT_RECOMMENDATIONS WHERE CUSTOMER_ID='${esc}' ORDER BY CONFIDENCE_SCORE DESC LIMIT 10`, 15000),
      ]),
    ]);

    const row = core[0] as Record<string, unknown> | undefined;
    if (!row) return NextResponse.json({ error: "not found" }, { status: 404 });

    const customer = { ...row };
    const device = row.DEVICE_MODEL ? { DEVICE_MODEL: row.DEVICE_MODEL, DEVICE_OS: row.DEVICE_OS, DEVICE_AGE_MONTHS: row.DEVICE_AGE_MONTHS, DEVICE_PAYMENT_REMAINING: row.DEVICE_PAYMENT_REMAINING, DEVICE_BRAND: row.DEVICE_BRAND } : null;
    const churn = row.CHURN_RISK_SCORE != null ? { CHURN_RISK_SCORE: row.CHURN_RISK_SCORE, CHURN_RISK_LEVEL: row.CHURN_RISK_LEVEL, PRIMARY_RISK_FACTORS: row.PRIMARY_RISK_FACTORS, PREDICTED_CHURN_DATE: row.PREDICTED_CHURN_DATE, RETENTION_PROBABILITY: row.RETENTION_PROBABILITY } : null;
    const memory = row.MEMORY_ID != null ? { MEMORY_ID: row.MEMORY_ID, CHANNEL: row.MEM_CHANNEL, LANGUAGE: row.LANGUAGE, LAST_INTENT: row.LAST_INTENT, ACTIVE_SPECIALIST: row.ACTIVE_SPECIALIST, LAST_SUMMARY: row.LAST_SUMMARY, OPEN_ACTIONS: row.OPEN_ACTIONS, NEXT_BEST_ACTION: row.MEM_NBA, LAST_CONTACT_AT: row.LAST_CONTACT_AT, ESCALATION_STATUS: row.ESCALATION_STATUS, REP_ASSIST_BRIEF: row.REP_ASSIST_BRIEF } : null;
    ["_src", "DEVICE_MODEL", "DEVICE_OS", "DEVICE_AGE_MONTHS", "DEVICE_PAYMENT_REMAINING", "DEVICE_BRAND", "CHURN_RISK_SCORE", "CHURN_RISK_LEVEL", "PRIMARY_RISK_FACTORS", "PREDICTED_CHURN_DATE", "RETENTION_PROBABILITY", "MEMORY_ID", "MEM_CHANNEL", "LANGUAGE", "LAST_INTENT", "ACTIVE_SPECIALIST", "LAST_SUMMARY", "OPEN_ACTIONS", "MEM_NBA", "LAST_CONTACT_AT", "ESCALATION_STATUS", "REP_ASSIST_BRIEF"].forEach((k) => delete customer[k]);

    const [usage, billing, engagement, qoe, cases, calls] = interactions;
    const [incidents, nba, actionLog, recommendations] = orchestration;

    return NextResponse.json({ customer, device, usage, billing, engagement, qoe, cases, churn, calls, incidents, nba, memory, actionLog, recommendations });
  } catch (e: unknown) {
    return NextResponse.json({ error: String(e) }, { status: 500 });
  }
}
